//ROVER
export const GET_ROVER_IMAGE_REQUEST = "GET_ROVER_IMAGE_REQUEST"
export const GET_ROVER_IMAGE_SUCCESS = "GET_ROVER_IMAGE_SUCCESS"
export const GET_ROVER_IMAGE_FAILURE = "GET_ROVER_IMAGE_FAILURE"